### PR TITLE
use network:app:appID:pubKey for subject

### PR DESCRIPTION
**Pull request by joe-p**
### Description

Please explain the changes you made.

- Adds the network to the subject (for example `did:algo:testnet:app:654583141:7d42e6e0f3c71d777de36849cf96e28b812453198cee2d2cc2b7b19438060007`)

### Checklist

- [x] Update internal methods to use network
- [x] Test all functions in `TUTORIAL.md` with CLI
- [x] Test resolver
- [x] Update config and CLI to handle multiple networks
- [x] Test multiple networks with CLI and resolver
- [x] Update README/TUTORIAL

### CODE REVIEW

**Comment by HashMapsData2Value** [comment]
Does pub key refer to the genesis hash?

**Comment by HashMapsData2Value** [comment]
I see that we are testing against 3 different versions of Go (1.19, 1.20, 1.21), resulting in triple the comments in terms of linting etc. Is this necessary?

**Comment by joe-p** [comment]
> Does pub key refer to the genesis hash?

No pubkey here is the ed25519 pubkey for the subject. The network is `mainnet` or `testnet`. Internally the genesis hash is used to make sure the algod being used is the correct genesis hash. 

> 
I see that we are testing against 3 different versions of Go (1.19, 1.20, 1.21), resulting in triple the comments in terms of linting etc. Is this necessary?

Probably not. I think because the main form of distribution is docker we can probably just pick one and stick with it.

**Comment by joe-p** [comment]
I have started to work on the spec to make sure we're all on the same page on the formatting. Once we're all good, I will update the code to reflect the spec.

**Comment by joe-p** [comment]
I've implemented the new spec

Manually verified omitted networks work with command `./algoid resolve did:algo:app:1845671812:da490f2d15a625459bf970a3d55e1a646dfd3a956d011546e953e945d39fdada`

**Pull request merged**
